---
- name: Resynchronize APT package index
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade APT packages
  become: yes
  apt:
    upgrade: yes

- name: Cleanup APT package cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
